#!/bin/bash

#Lance le client mail pour les administrateurs
# Couleur R=rouge / B=bleu / Y=jaune / N=classique
R="\033[0;31m"
B="\033[0;34m"
Y="\033[0;33m"
N="\033[0m"

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    echo "entrer soit eliott, baptiste"
    echo "(permet d'acceder aux boites mails)"
    exit 1

elif [ $1 = "eliott" ] 
then
        if [ -d "/var/mail/vhosts/mes-b2.ephec-ti.be/eliott/" ]
        then
                printf "local mail user$B found$N, connecting...\n"
                sleep 1
                mutt -f /var/mail/vhosts/mes-b2.ephec-ti.be/eliott/
        else
                printf "local mail user$R not found$N, connecting to remote mail server...\n"
                printf "PS: Your username is :$Y eliott@mes-b2.ephec-ti.be$N\n"
                sleep 2
                mutt -f imaps://135.125.239.192:993
        fi

elif [ $1 = "baptiste" ]
then
        if [ -d "/var/mail/vhosts/mes-b2.ephec-ti.be/baptiste/" ]
        then
                printf "local mail user$B found$N, connecting...\n"
                sleep 1
                mutt -f /var/mail/vhosts/mes-b2.ephec-ti.be/baptiste/
        else
                printf "local mail user$R not found$N, connecting to remote mail server...\n"
                printf "PS: Your username is :$Y baptiste@mes-b2.ephec-ti.be$N\n"
                sleep 2
                mutt -f imaps://135.125.239.192:993
        fi
fi