# Docker-compose pour la configuration du service mail du projet Woody Toys

version: '2'

services:
  mail:
    build: .
    ports:
      - "25:25"   #PORT UDP SANS CHIFFREMENT POUR SMTP 
      - "465:465" #PORT UDP AVEC CHIFFREMENT IMPLICITE POUR SMTP
      - "587:587" #PORT UDP AVEC CHIFFREMENT EXPLICITE POUR SMTP
      - "143:143" #PORT TCP POUR IMAP (RECEPTION)

    environment:
      MYSQL_ROOT_PASSWORD: aOmnATr
    hostname: mail

    container_name: dockerMail

## Commentaires
# Port 25 : port UDP SANS chiffrement pour SMTP
# Port 143 : port TCP et est utilisé afin de réceptionné les emails (IMAP)
# Port 465 : port UDP AVEC chiffrement pour SMTP
# Port 587 : port UDP AVEC chiffrement pour SMTP
