version: '3.8'

##############################################
##       Docker Services Configuration      ##
##############################################

services:

  mail:
    build:
      context: ./Mail
      dockerfile: Dockerfile
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
         
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    hostname: mail
    container_name: mail
